/* auto-generated by NAPI-RS */
/* eslint-disable */
/** JavaScript-facing request object */
export declare class JsRequest {
  getMethod(): string
  getUrl(): string
  getHeader(name: string): string | null
  getQuery(): string
}

/** JavaScript-facing response object */
export declare class JsResponse {
  writeStatus(status: string): this
  writeHeader(key: string, value: string): this
  onAborted(callback: () => void): void
  write(data: string | Buffer): boolean
  end(data?: string | Buffer | undefined | null): void
  cork(callback: () => void): void
  tryEnd(data: Buffer, totalSize: number): boolean
  getWriteOffset(): number
  onData(callback: (arg0: Buffer, arg1: boolean) => void): void
  isAborted(): boolean
  get aborted(): boolean
  set aborted(value: boolean)
}

/** The main server class exposed to JavaScript */
export declare class RyoServer {
  constructor()
  /** Set the directory for static file serving */
  setStaticDir(dir: string): void
  /** Register a GET route handler */
  get(pattern: string, handler: (arg0: JsResponse, arg1: JsRequest) => void): void
  /** Register a POST route handler */
  post(pattern: string, handler: (arg0: JsResponse, arg1: JsRequest) => void): void
  /** Register a handler for any HTTP method */
  any(pattern: string, handler: (arg0: JsResponse, arg1: JsRequest) => void): void
  /** Start the server */
  listen(port: number): void
}
