/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JsResponse {
  writeStatus(status: string): JsResponse
  writeHeader(key: string, value: string): JsResponse
  write(chunk: string | Buffer): boolean
  end(body?: string | Buffer | undefined | null): void
  cork(callback: () => void): void
  isAborted(): boolean
  onAborted(callback: () => void): void
  onData(callback: (arg0: Buffer, arg1: boolean) => void): void
  getWriteOffset(): number
  tryEnd(data: Buffer, totalSize: number): [boolean, boolean]
  onWritable(callback: (arg0: number) => boolean): void
  readJson(contextType: string, cb: (arg0: string) => void, err: (arg0: string) => void): void
}

export declare class RyoServer {
  constructor()
  setStaticDir(dir: string): void
  get(path: string, handler: (arg0: JsResponse, arg1: JsRequest) => void): void
  post(path: string, handler: (arg0: JsResponse, arg1: JsRequest) => void): void
  /** Start the HTTP server */
  listen(port: number, callback?: ((arg0: string) => void) | undefined | null): void
}

export interface JsRequest {
  method: string
  path: string
  params: Array<Param>
}

export interface Param {
  key: string
  value: string
}
