/* auto-generated by NAPI-RS */
/* eslint-disable */
/** JavaScript-facing request object */
export declare class JsRequest {
  getMethod(): string
  getUrl(): string
  getHeader(name: string): string | null
  getQuery(): string
}

/** JavaScript-facing response object */
export declare class JsResponse {
  writeStatus(status: string): this
  writeHeader(key: string, value: string): this
  write(data: Buffer): boolean
  end(data?: string | Buffer | undefined | null): void
  cork(callback: any): void
}

/** The main server class exposed to JavaScript */
export declare class RyoServer {
  constructor()
  /** Set the directory for static file serving */
  setStaticDir(dir: string): void
  /** Register a GET route handler */
  get(pattern: string, handler: (arg0: JsResponse, arg1: JsRequest) => void): void
  /** Register a POST route handler */
  post(pattern: string, handler: (arg0: JsResponse, arg1: JsRequest) => void): void
  /** Register a handler for any HTTP method */
  any(pattern: string, handler: (arg0: JsResponse, arg1: JsRequest) => void): void
  /** Start the server */
  listen(port: number): Promise<void>
}
